In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.arange(6)
a2 = a[np.newaxis,:]

In [4]:
a2.shape

(1, 6)

In [5]:
a = np.array([1,2,3,4,5,6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[0]

array([1, 2, 3, 4])

In [10]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [11]:
a.shape

(3, 4)

In [12]:
a[0,1]

2

In [13]:
a[0]

array([1, 2, 3, 4])

In [14]:
a = np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.empty(2)

array([ 3.02514832e-147, -1.45840155e-038])

In [19]:
np.arange(4)

array([0, 1, 2, 3])

In [20]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [22]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
x=np.ones(2, dtype=np.int64)

In [29]:
x

array([1, 1], dtype=int64)

In [31]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [32]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [35]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [37]:
x

array([[1, 2],
       [3, 4]])

In [38]:
y

array([[5, 6]])

In [39]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [41]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [42]:
array_example.ndim 

3

In [43]:
array_example.size

24

In [44]:
array_example.shape

(3, 2, 4)

In [45]:
a = np.arange(6)

In [46]:
a

array([0, 1, 2, 3, 4, 5])

In [48]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [49]:
a

array([0, 1, 2, 3, 4, 5])

In [50]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])

In [52]:
a.shape

(6,)

In [53]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [54]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [55]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [57]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [58]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [59]:
data = np.array([1, 2, 3])

In [60]:
data[1]

2

In [61]:
data

array([1, 2, 3])

In [62]:
data[0:2]

array([1, 2])

In [63]:
data[1:]

array([2, 3])

In [65]:
data[-2:]

array([2, 3])

In [66]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [67]:
print(a[a < 5])

[1 2 3 4]


In [77]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [78]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [68]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [70]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [71]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [74]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [75]:
print(a[b])

[1 2 3 4]


In [76]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [84]:
b = np.nonzero(a<5)

In [85]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [86]:
list_of_coordinates = list(zip(b[0],b[1]))

In [88]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [89]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [90]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [92]:
a1 = np.array([[1, 1],
               [2, 2]])

In [93]:
a2 = np.array([[3, 3],
               [4, 4]])

In [94]:
a1

array([[1, 1],
       [2, 2]])

In [95]:
a2

array([[3, 3],
       [4, 4]])

In [96]:
np.concatenate((a1,a2),axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [97]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [98]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [99]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [100]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [101]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [103]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [104]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [106]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [107]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
a[:,3]

array([ 4,  8, 12])

In [111]:
b1 = a[0,:]

In [112]:
b1

array([99,  2,  3,  4])

In [113]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
b1 = a[0,:].copy()

In [115]:
b1

array([99,  2,  3,  4])

In [116]:
b1[0]=0

In [117]:
b1

array([0, 2, 3, 4])

In [118]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a.copy()

In [119]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [120]:
data - ones

array([0, 1])

In [121]:
data * data

array([1, 4])

In [122]:
data / data

array([1., 1.])

In [124]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [125]:
b = np.array([[1, 1], [2, 2]])

In [126]:
b.sum(axis=0)

array([3, 3])

In [127]:
b.sum(axis=1)

array([2, 4])

In [128]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [129]:
data.max()

2.0

In [130]:
data.min()

1.0

In [131]:
data.sum()

3.0

In [132]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [133]:
a.sum()

4.8595784

In [134]:
a.min()

0.05093587

In [135]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [136]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [137]:
data[0, 1]

2

In [138]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [139]:
data[0:2, 0]

array([1, 3])

In [140]:
data.max()

6

In [141]:
data.min()

1

In [142]:
data.sum()

21

In [143]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [144]:
data.max(axis=0)

array([5, 6])

In [145]:
data.max(axis=1)

array([2, 5, 6])

In [146]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [147]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [148]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [149]:
np.ones(3)

array([1., 1., 1.])

In [150]:
np.zeros(3)

array([0., 0., 0.])

In [152]:
rng = np.random.default_rng()
rng.random(3) 

array([0.98933654, 0.93209509, 0.32072083])

In [153]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [154]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [155]:
rng.random((3, 2)) 

array([[0.37080282, 0.5945906 ],
       [0.16074754, 0.5374782 ],
       [0.18383142, 0.96872785]])

In [158]:
rng.integers(5, size=(2, 4)) 

array([[4, 4, 0, 3],
       [0, 2, 3, 3]], dtype=int64)

In [159]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [160]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [161]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [162]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [163]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [164]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [165]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [166]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [167]:
print(indices)

[0 1 2]


In [168]:
print(occurrence_count)

[2 1 1]


In [169]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [172]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [173]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [174]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [175]:
reversed_arr = np.flip(arr)

In [176]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [177]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [178]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [179]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [180]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [181]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [182]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [183]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [184]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [185]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [186]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [187]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [188]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
